// Building is part of this packaging integration test: manifests and entrypoint paths
// are generated by WXT and cannot be verified from TypeScript checking alone.
import { strict as assert } from 'node:assert';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import communityService from '../../data/community-service.json';
const root = join(import.meta.dir, '..');
for (const target of ['chrome', 'firefox']) {
  const process = Bun.spawn(['bun', 'run', `build:${target === 'chrome' ? 'chromium' : 'firefox'}`], { cwd: root, stdout: 'pipe', stderr: 'pipe' });
  const [stdout, stderr, exit] = await Promise.all([new Response(process.stdout).text(), new Response(process.stderr).text(), process.exited]);
  assert.equal(exit, 0, `${target} packaging failed\n${stdout}\n${stderr}`);
  const directory = join(root, '.output', `${target}-mv3`);
  const manifest = JSON.parse(readFileSync(join(directory, 'manifest.json'), 'utf8')) as { permissions: string[]; host_permissions: string[]; optional_permissions: string[]; content_scripts?: unknown[]; background: { service_worker?: string; scripts?: string[] }; action: { default_popup: string } };
  assert.equal(manifest.content_scripts?.length ?? 0, 0, 'Store scripts must not load before opt-in');
  assert(!manifest.permissions.includes('tabs'), 'No passive all-tab access');
  assert(manifest.optional_permissions.includes('nativeMessaging'), 'Companion must be optional');
  assert.deepEqual([...manifest.host_permissions].sort(), [
    'https://world.openfoodfacts.org/*', 'https://world.openbeautyfacts.org/*', 'https://world.openproductsfacts.org/*',
    `${new URL(communityService.baseUrl).origin}/*`,
  ].sort(), 'Default host access is limited to Open Facts and the configured community service');
  assert(existsSync(join(directory, manifest.action.default_popup)));
  assert(existsSync(join(directory, 'app.html')));
  assert(existsSync(join(directory, 'content-scripts/store.js')), 'Dynamic store entrypoint must exist');
  if (target === 'chrome') assert(manifest.background.service_worker);
  else assert(manifest.background.scripts?.length);
  console.log(`${target}: generated manifest, permissions, background and UI entrypoints verified`);
}
